spring:
  profiles:
    active: prod

reader:
  app:
    workDir: "."
    showUI: false
    debug: false
    packaged: false
    secure: true
    inviteCode: "w0SIOhQxvys1gpm9"
    secureKey: "w0SIOhQxvys1gpm9"
    proxy: false
    proxyType: "HTTP"
    proxyHost: ""
    proxyPort: ""
    proxyUsername: ""
    proxyPassword: ""
    cacheChapterContent: true
    userLimit: 50
    userBookLimit: 200
    debugLog: false
    autoClearInactiveUser: 0
    mongoUri: "mongodb://mongo:HIBkWSVDVvLlfTp7dGME@containers-us-west-86.railway.app:7104"
    mongoDbName: "reader"

  server:
    port: 8080
    webUrl: http://localhost:${reader.server.port}

logging:
  path: "${reader.app.workDir}/logs"